<?php
// modul/program/backup.php - VERSI DENGAN PERBAIKAN DOWNLOAD & DELETE


// Proteksi - hanya IT Admin yang bisa akses
if (!isset($_SESSION['username']) || $_SESSION['id_role'] != 1) {
    header("Location: login.php");
    exit;
}

include __DIR__ . '/../../koneksi.php';

$success_msg = "";
$error_msg = "";
$backup_files = [];

// ======================================================================
// TENTUKAN PATH BACKUP
// ======================================================================
$configQuery = "SELECT backup_path FROM sys_config WHERE id_config = 1";
$configResult = mysqli_query($conn, $configQuery);
$config = mysqli_fetch_assoc($configResult);

if ($config && !empty($config['backup_path'])) {
    $backupPathFromDB = $config['backup_path'];
    if (strpos($backupPathFromDB, './') === 0) {
        $backupPath = __DIR__ . '/../../' . substr($backupPathFromDB, 2);
    } else {
        $backupPath = __DIR__ . '/../../' . $backupPathFromDB;
    }
} else {
    $backupPath = __DIR__ . '/../../backup/';
}

$backupPath = str_replace('\\', '/', $backupPath);
if (substr($backupPath, -1) != '/') {
    $backupPath .= '/';
}

// ======================================================================
// FUNGSI BACKUP
// ======================================================================
function backupDatabasePHP($conn, $backupPath) {
    global $db;
    
    if (!file_exists($backupPath)) {
        if (!mkdir($backupPath, 0777, true)) {
            return false;
        }
    }
    
    if (!is_writable($backupPath)) {
        return false;
    }
    
    $date = date('Y-m-d_H-i-s');
    $filename = "backup_{$db}_{$date}.sql";
    $filepath = $backupPath . $filename;
    
    $tables = [];
    $result = mysqli_query($conn, "SHOW TABLES");
    if (!$result) {
        return false;
    }
    
    while ($row = mysqli_fetch_array($result)) {
        $tables[] = $row[0];
    }
    
    $sql = "-- =============================================\n";
    $sql .= "-- Database Backup: {$db}\n";
    $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
    $sql .= "-- Generated by: " . $_SESSION['username'] . "\n";
    $sql .= "-- =============================================\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";
    
    foreach ($tables as $table) {
        $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
        
        $createResult = mysqli_query($conn, "SHOW CREATE TABLE `{$table}`");
        if ($createResult) {
            $createRow = mysqli_fetch_assoc($createResult);
            if (isset($createRow['Create Table'])) {
                $sql .= $createRow['Create Table'] . ";\n\n";
            } elseif (isset($createRow[1])) {
                $sql .= $createRow[1] . ";\n\n";
            } else {
                $sql .= "CREATE TABLE `{$table}` (id INT);\n\n";
            }
        }
        
        $dataResult = mysqli_query($conn, "SELECT * FROM `{$table}`");
        if ($dataResult && mysqli_num_rows($dataResult) > 0) {
            while ($row = mysqli_fetch_assoc($dataResult)) {
                $sql .= "INSERT INTO `{$table}` VALUES (";
                $values = [];
                foreach ($row as $value) {
                    if ($value === null) {
                        $values[] = "NULL";
                    } else {
                        $values[] = "'" . mysqli_real_escape_string($conn, $value) . "'";
                    }
                }
                $sql .= implode(', ', $values) . ");\n";
            }
        }
        $sql .= "\n";
    }
    
    $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";
    
    if (file_put_contents($filepath, $sql)) {
        if (class_exists('ZipArchive')) {
            $zip = new ZipArchive();
            $zipFilename = str_replace('.sql', '.zip', $filepath);
            if ($zip->open($zipFilename, ZipArchive::CREATE) === TRUE) {
                $zip->addFile($filepath, $filename);
                $zip->close();
                unlink($filepath);
                return $zipFilename;
            }
        }
        return $filepath;
    }
    
    return false;
}

function backupDatabase($conn, $backupPath) {
    global $db, $host, $user, $pass;
    
    if (!file_exists($backupPath)) {
        if (!mkdir($backupPath, 0777, true)) {
            return false;
        }
    }
    
    if (!is_writable($backupPath)) {
        return false;
    }
    
    $date = date('Y-m-d_H-i-s');
    $filename = "backup_{$db}_{$date}.sql";
    $filepath = $backupPath . $filename;
    
    $mysqldumpPaths = [
        'C:/xampp/mysql/bin/mysqldump.exe',
        'C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe',
        'C:/Program Files/MySQL/MySQL Server 5.7/bin/mysqldump.exe',
    ];
    
    $mysqldump = 'mysqldump';
    foreach ($mysqldumpPaths as $path) {
        if (file_exists($path)) {
            $mysqldump = $path;
            break;
        }
    }
    
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        $mysqldump = '"' . $mysqldump . '"';
        $filepath = str_replace('/', '\\', $filepath);
    }
    
    $command = "{$mysqldump} --host={$host} --user={$user} --password={$pass} --add-drop-table --add-locks --create-options --disable-keys --extended-insert --single-transaction --quick {$db} > \"{$filepath}\" 2>&1";
    
    $output = null;
    $returnCode = null;
    exec($command, $output, $returnCode);
    
    if ($returnCode === 0 && file_exists($filepath) && filesize($filepath) > 0) {
        if (class_exists('ZipArchive')) {
            $zip = new ZipArchive();
            $zipFilename = str_replace('.sql', '.zip', $filepath);
            if ($zip->open($zipFilename, ZipArchive::CREATE) === TRUE) {
                $zip->addFile($filepath, $filename);
                $zip->close();
                unlink($filepath);
                return $zipFilename;
            }
        }
        return $filepath;
    }
    
    return backupDatabasePHP($conn, $backupPath);
}

// ======================================================================
// PROSES BACKUP
// ======================================================================
if (isset($_GET['action']) && $_GET['action'] == 'backup') {
    if (!file_exists($backupPath)) {
        mkdir($backupPath, 0777, true);
    }
    
    if (is_writable($backupPath)) {
        $result = backupDatabase($conn, $backupPath);
        if ($result) {
            $success_msg = "✅ Backup berhasil dibuat! File: " . basename($result);
        } else {
            $error_msg = "❌ Gagal membuat backup database!";
        }
    } else {
        $error_msg = "❌ Folder backup tidak dapat ditulis!";
    }
}

// ======================================================================
// PROSES DOWNLOAD - DIPERBAIKI
// ======================================================================
if (isset($_GET['download']) && !empty($_GET['download'])) {
    $filename = basename($_GET['download']);
    $filepath = $backupPath . $filename;
    
    // Cek apakah file ada
    if (file_exists($filepath)) {
        // Set header untuk download
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . filesize($filepath));
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        
        // Baca file dan kirim ke browser
        readfile($filepath);
        exit;
    } else {
        // Jika file tidak ditemukan, redirect dengan pesan error
        header("Location: " . $_SERVER['PHP_SELF'] . "?error=File tidak ditemukan!");
        exit;
    }
}

// ======================================================================
// PROSES DELETE - DIPERBAIKI
// ======================================================================
if (isset($_GET['delete']) && !empty($_GET['delete'])) {
    $filename = basename($_GET['delete']);
    $filepath = $backupPath . $filename;
    
    if (file_exists($filepath)) {
        if (unlink($filepath)) {
            $success_msg = "✅ File backup berhasil dihapus!";
        } else {
            $error_msg = "❌ Gagal menghapus file backup!";
        }
    } else {
        $error_msg = "❌ File tidak ditemukan!";
    }
}

// ======================================================================
// AMBIL DAFTAR FILE BACKUP
// ======================================================================
if (file_exists($backupPath)) {
    $files = scandir($backupPath);
    if ($files) {
        foreach ($files as $file) {
            if ($file != '.' && $file != '..' && !is_dir($backupPath . $file)) {
                $filePath = $backupPath . $file;
                $backup_files[] = [
                    'name' => $file,
                    'size' => filesize($filePath),
                    'modified' => date('Y-m-d H:i:s', filemtime($filePath)),
                    'type' => pathinfo($file, PATHINFO_EXTENSION)
                ];
            }
        }
        usort($backup_files, function($a, $b) {
            return strtotime($b['modified']) - strtotime($a['modified']);
        });
    }
}

$lastBackup = !empty($backup_files) ? $backup_files[0]['modified'] : 'No backup yet';
$totalSize = array_sum(array_column($backup_files, 'size'));

// ======================================================================
// CEK ERROR MESSAGE DARI URL
// ======================================================================
if (isset($_GET['error'])) {
    $error_msg = "❌ " . $_GET['error'];
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Backup Database</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        .debug-info {
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 4px;
            padding: 10px;
            margin: 10px 0;
            font-family: monospace;
            font-size: 12px;
        }
        .table-crystal {
            font-size: 12px;
        }
        .table-crystal th,
        .table-crystal td {
            padding: 0.3rem 0.5rem !important;
            vertical-align: middle;
        }
        .btn-micro {
            padding: 0.1rem 0.3rem;
            font-size: 10px;
            line-height: 1.2;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h4"><i class="fa fa-database text-success"></i> Backup Database</h1>
        <div>
            <a href="http://192.168.31.200/cahaya/index.php?page=backup&debug=1&action=backup" class="btn btn-primary btn-sm" onclick="return confirm('Yakin ingin melakukan backup database? Proses ini mungkin memakan waktu.')">
                <i class="fa fa-database"></i> Backup Sekarang
            </a>
            <a href="http://192.168.31.200/cahaya/index.php?page=backup&debug=1" class="btn btn-warning btn-sm" title="Debug Mode">
                <i class="fa fa-bug"></i> Debug
            </a>
            <button class="btn btn-info btn-sm" onclick="location.reload()">
                <i class="fa fa-sync"></i> Refresh
            </button>
        </div>
    </div>

    <?php if ($success_msg): ?>
        <div class="alert alert-success alert-dismissible fade show p-2 small" role="alert">
            <i class="fa fa-check-circle me-1"></i> <?= $success_msg; ?>
            <button type="button" class="btn-close p-2" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <?php if ($error_msg): ?>
        <div class="alert alert-danger alert-dismissible fade show p-2 small" role="alert">
            <i class="fa fa-exclamation-circle me-1"></i> <?= $error_msg; ?>
            <button type="button" class="btn-close p-2" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <!-- Debug Info -->
    <?php if (isset($_GET['debug'])): ?>
    <div class="alert alert-info p-2 small">
        <strong>🔍 DEBUG INFORMATION:</strong><br>
        📁 Backup Path from DB: <code><?= $config['backup_path'] ?? 'Not Set' ?></code><br>
        📂 Full Backup Path: <code><?= $backupPath ?></code><br>
        📍 Real Path: <code><?= realpath($backupPath) ?: 'Not Found' ?></code><br>
        📂 Folder Exists: <?= file_exists($backupPath) ? '✅ Yes' : '❌ No' ?><br>
        ✏️ Is Writable: <?= is_writable($backupPath) ? '✅ Yes' : '❌ No' ?><br>
        📊 Database: <code><?= $db ?></code><br>
        📁 Files: <?= count($backup_files) ?> file(s)
    </div>
    <?php endif; ?>

    <!-- Info Folder -->
    <div class="alert alert-secondary p-2 small">
        <i class="fa fa-folder me-1"></i>
        <strong>Folder Backup:</strong> <code><?= $backupPath ?></code>
        <span class="badge bg-<?= is_writable($backupPath) ? 'success' : 'danger' ?> ms-2">
            <?= is_writable($backupPath) ? '✅ Writable' : '❌ Not Writable' ?>
        </span>
        <span class="badge bg-info ms-2"><?= count($backup_files) ?> files</span>
    </div>

    <div class="row">
        <!-- Status -->
        <div class="col-md-4">
            <div class="card shadow-sm mb-3">
                <div class="card-header bg-primary text-white fw-bold py-2">
                    <i class="fa fa-info-circle me-2"></i> Status Backup
                </div>
                <div class="card-body p-3">
                    <table class="table table-sm table-bordered table-crystal mb-0">
                        <tr>
                            <td width="45%"><strong>Total Backup</strong></td>
                            <td><span class="badge bg-info"><?= count($backup_files) ?></span></td>
                        </tr>
                        <tr>
                            <td><strong>Terakhir Backup</strong></td>
                            <td><?= $lastBackup ?></td>
                        </tr>
                        <tr>
                            <td><strong>Total Size</strong></td>
                            <td>
                                <?php
                                if ($totalSize >= 1073741824) {
                                    echo number_format($totalSize / 1073741824, 2) . ' GB';
                                } elseif ($totalSize >= 1048576) {
                                    echo number_format($totalSize / 1048576, 2) . ' MB';
                                } elseif ($totalSize >= 1024) {
                                    echo number_format($totalSize / 1024, 2) . ' KB';
                                } else {
                                    echo $totalSize . ' B';
                                }
                                ?>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            
            <div class="card shadow-sm">
                <div class="card-header bg-warning text-dark fw-bold py-2">
                    <i class="fa fa-lightbulb me-2"></i> Tips Backup
                </div>
                <div class="card-body p-2">
                    <ul class="small mb-0 ps-3">
                        <li>Lakukan backup secara rutin minimal 1x sehari</li>
                        <li>Simpan backup di luar server untuk keamanan</li>
                        <li>Periksa ukuran file backup secara berkala</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Daftar File -->
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-dark text-white fw-bold py-2 d-flex justify-content-between align-items-center">
                    <span><i class="fa fa-list me-2"></i> Daftar File Backup</span>
                    <span class="badge bg-light text-dark"><?= count($backup_files) ?> files</span>
                </div>
                <div class="card-body p-0">
                    <?php if (empty($backup_files)): ?>
                        <div class="text-center p-4 text-muted">
                            <i class="fa fa-inbox fa-2x mb-2"></i>
                            <p>Belum ada file backup. Klik tombol <strong>"Backup Sekarang"</strong>.</p>
                        </div>
                    <?php else: ?>
                        <div class="table-responsive">
                            <table class="table table-sm table-hover table-crystal mb-0">
                                <thead class="table-dark">
                                    <tr>
                                        <th width="5%">#</th>
                                        <th>Nama File</th>
                                        <th width="15%">Ukuran</th>
                                        <th width="20%">Tanggal</th>
                                       
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($backup_files as $index => $file): ?>
                                        <tr>
                                            <td><?= $index + 1 ?></td>
                                            <td>
                                                <i class="fa fa-<?= $file['type'] == 'zip' ? 'file-archive' : 'file-code' ?> text-info me-1"></i>
                                                <code><?= $file['name'] ?></code>
                                            </td>
                                            <td>
                                                <?php
                                                $size = $file['size'];
                                                if ($size >= 1073741824) {
                                                    echo number_format($size / 1073741824, 2) . ' GB';
                                                } elseif ($size >= 1048576) {
                                                    echo number_format($size / 1048576, 2) . ' MB';
                                                } elseif ($size >= 1024) {
                                                    echo number_format($size / 1024, 2) . ' KB';
                                                } else {
                                                    echo $size . ' B';
                                                }
                                                ?>
                                            </td>
                                            <td><?= $file['modified'] ?></td>
                                           
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>